import re


_PDF_COMMENT = b'% Generated by malicious-pdf - https://github.com/jonaslejon/malicious-pdf\n'
_PDF_INFO = b' /Info << /Creator (malicious-pdf) /Producer (https://github.com/jonaslejon/malicious-pdf) >>'
_FOOTER_LABEL = b'Generated by malicious-pdf - https://github.com/jonaslejon/malicious-pdf'


def _append_visible_footer(data):
    """Append a visible credit line to the first uncompressed text content stream.
    Returns possibly-modified bytes. Leaves xref offsets as-is (viewers tolerate the
    drift via fallback scan; this matches the existing comment/Info injection)."""
    obj_re = re.compile(
        rb'(\d+\s+0\s+obj\s*<<)([^>]*?)(/Length\s+)(\d+)([^>]*?)(>>\s*\nstream\n)(.*?)(\nendstream)',
        re.DOTALL,
    )
    for m in obj_re.finditer(data):
        dict_body = m.group(2) + m.group(5)
        body = m.group(7)
        if b'/Filter' in dict_body:
            continue
        if b'BT' not in body or b'ET' not in body:
            continue
        font_match = re.search(rb'(/F\d+)\s+\d+(?:\.\d+)?\s+Tf', body)
        if not font_match:
            continue
        font_name = font_match.group(1)
        footer_ops = b'\n  BT ' + font_name + b' 8 Tf 30 15 Td (' + _FOOTER_LABEL + b') Tj ET'
        new_body = body + footer_ops
        new_obj = (m.group(1) + m.group(2) + m.group(3)
                   + str(len(new_body)).encode()
                   + m.group(5) + m.group(6) + new_body + m.group(8))
        return data[:m.start()] + new_obj + data[m.end():]
    return data


def inject_credit(output_dir, file_extensions):
    """Inject credit comment, Info dict metadata, and visible footer into generated PDFs."""
    for filepath in output_dir.iterdir():
        if filepath.suffix == '.svg':
            continue
        try:
            data = filepath.read_bytes()

            # Method 3: Insert comment after %PDF-x.x header line
            newline_idx = data.index(b'\n') + 1
            data = data[:newline_idx] + _PDF_COMMENT + data[newline_idx:]

            # Method 1: Insert /Info in trailer dict
            # Find the last trailer and inject /Info before its final >>
            trailer_idx = data.rfind(b'trailer')
            if trailer_idx != -1:
                trailer_section = data[trailer_idx:]
                if b'/Info' not in trailer_section:
                    # Find the last >> in the trailer section (the outermost dict close)
                    last_close = trailer_section.rfind(b'>>')
                    if last_close != -1:
                        insert_pos = trailer_idx + last_close
                        data = data[:insert_pos] + _PDF_INFO + b'\n  ' + data[insert_pos:]

            # Method 4: Append visible footer line to the page's text content stream
            data = _append_visible_footer(data)

            filepath.write_bytes(data)
        except Exception:
            pass  # Skip files that don't have standard PDF structure (e.g., test11 EICAR)
